//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Algs4NetUnitTests {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TestResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TestResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Algs4NetUnitTests.TestResources", typeof(TestResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AK WA
        ///AL FL
        ///AL GA
        ///AL MS
        ///AL TN
        ///AR LA
        ///AR MO
        ///AR MS
        ///AR OK
        ///AR TN
        ///AR TX
        ///AZ CA
        ///AZ CO
        ///AZ NM
        ///AZ NV
        ///AZ UT
        ///CA HI
        ///CA NV
        ///CA OR
        ///CO KS
        ///CO NE
        ///CO NM
        ///CO OK
        ///CO UT
        ///CO WY
        ///CT MA
        ///CT NY
        ///CT RI
        ///DC MD
        ///DC VA
        ///DE MD
        ///DE NJ
        ///DE PA
        ///FL GA
        ///GA NC
        ///GA SC
        ///GA TN
        ///IA IL
        ///IA MN
        ///IA MO
        ///IA NE
        ///IA SD
        ///IA WI
        ///ID MT
        ///ID NV
        ///ID OR
        ///ID UT
        ///ID WA
        ///ID WY
        ///IL IN
        ///IL KY
        ///IL MO
        ///IL WI
        ///IN KY
        ///IN MI
        ///IN OH
        ///KS MO
        ///KS NE
        ///KS OK
        ///KY MO
        ///KY OH
        ///KY TN
        ///KY VA
        ///KY WV
        ///LA MS
        ///LA TX
        ///MA NH
        ///MA NY
        ///MA RI
        ///MA VT
        ///MD PA
        ///MD VA
        ///MD WV
        ///M [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string us_state_neighbors {
            get {
                return ResourceManager.GetString("us_state_neighbors", resourceCulture);
            }
        }
    }
}
